### ISSUE TITLE
I/O bug : printing twice in a row and wait for user input -> bug in second printing

### ISSUE THREAD

**Issue by EmmanuelLazard** [TheThirdOne/rars#108]
Hello,
Maybe it's just me but I have the following bug:
- I display a string (that's not necessary for the bug, just easier to follow),
- I then wait for the user to enter a string (ReadString ecall) [2 chars max, not an issue],
- I print an integer (PrintInt ecall),
- I print back the user-entered string,
- And I loop back.

Now, what happens is that after printing the integer, the display stops (as if the computer was waiting for a user input) instead of displaying the user-entered string (if I print a second integer instead, it's the same, computer waits before printing it). I then press enter and the program continues but because of this extra carriage-return, displayed strings are shifted by one (previous one is displayed instead of the latest one)!

```
.globl _start

_start:
# First display a string '?'
	la	a0, str		# display question mark
	addi	a7, x0, 4	# PrintString
	ecall                   # sys call

# Then wait for a user entered string
	la	a0, buff
	addi	a1, zero, 4
	addi	a7, x0, 8	# ReadString
	ecall			# sys call

# Now print an integer
	addi	a0, zero, 1
	addi	a7, x0, 1	# PrintInt
	ecall			# sys call

# and print back user string
	la	a0, buff	# print back user string
	addi	a7, x0, 4	# PrintString
	ecall                   # sys call
	
# go back to start
	jal	zero, _start

.data
buff:	.space	4
str:	.string	"\n? "

```

**Comment by EmmanuelLazard** [comment]
I managed to even simplify the example. Issue is not in PrintInt.
I just have to print two strings and then wait for a user input.
The second string is not printed before the computer waits for the user input (and then prints it afterwards!).

```
.globl _start

_start:
# Display two strings
	la	a0, str		# display string
	addi	a7, x0, 4	# PrintString
	ecall                   # sys call

	la	a0, str		# display string
	addi	a7, x0, 4	# PrintString
	ecall                   # sys call

# Then wait for a user entered string
	la	a0, buff
	addi	a1, zero, 4
	addi	a7, x0, 8	# ReadString
	ecall			# sys call

# End program
	addi	a7, x0, 10      # Exit
	ecall                   # sys call


.data
buff:	.space	4
str:	.string	"String\n"

```

I have this issue on macOS and Ubuntu Linux.

**Comment by TheThirdOne** [comment]
Thanks for the detailed reproduction instructions. They made it very easy to confirm and understand why this issue is happening.

This is related to #80 (not the primary issue, but the reason why it is still open).  To solve that issue I introduced a cache for commandline output because the GUI does not handle many small additions well. It periodically flushes on instruction execution so it doesn't actually flush in a reasonable amount of time when a blocking IO system call is used.

I could very easily fix this issue by flushing the cache whenever a user input system call is used, but that seems fragile. I would be inclined to flush on every non-stdout-writing system call. I will give this a little more thought before I start making a solution.

**Comment by EmmanuelLazard** [comment]
Yes, I forgot to tell you that the bug only appears when running at full speed and not when the slidebar is at a slower level (even 30 inst/s is ok).
Issue is linked to the delay in print2gui() in SystemIO.java and the delay before deciding to print:

```
private static void print2Gui(String output){
        long time = System.currentTimeMillis();
        if (time > lasttime) {
            Globals.getGui().getMessagesPane().postRunMessage(buffer+output);
            buffer = "";
            lasttime = time +100;
        } else {
            buffer += output;
        }
    }
```

If I change line 453 to 
`            lasttime = time +1;`
the two strings are printed; if I write +2 instead, again just the first string is printed only.
I may depend on the host computer speed, mine is pretty rapid.

**Comment by TheThirdOne** [comment]
> Yes, I forgot to tell you that the bug only appears when running at full speed and not when the slidebar is at a slower level (even 30 inst/s is ok).

This makes sense because `1000ms / 30 instructions * 3 instructions between ecalls = 100 ms`. 30 instructions per second should just barely be ok.

> Issue is linked to the delay in print2gui() in SystemIO.java and the delay before deciding to print:

I don't plan to change anything in print2gui. Instead I plan to call `SystemIO.flush()` in order to make sure the 100ms maximum delay is actually followed.

**Comment by EmmanuelLazard** [comment]
Another option would be to add a small delay if the function is called too early:

```
 private static void print2Gui(String output){
    long time = System.currentTimeMillis();
    if (time < lasttime) {
        try {
            Thread.sleep(lasttime - time);
        } catch(InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
    }
    Globals.getGui().getMessagesPane().postRunMessage(buffer+output);
    buffer = "";
    lasttime = time +100;
}
```
