### ISSUE TITLE
ReadString syscall not documented

### ISSUE THREAD

**Issue by Obijuan** [TheThirdOne/rars#11]
The ReadString syscall is fully working but the documentation in the syscall table say it is not available

I've tested this service and it works perfectly

**Comment by TheThirdOne** [comment]
Is there a reason that the Read syscall isn't being used instead? I originally intended to delete ReadString as per this [TODO](https://github.com/TheThirdOne/rars/blob/ac339c751bc8ffaddad390f5fb5b5c939bb2cf51/rars/riscv/syscalls/SyscallReadString.java#L48). 

The only difference between ReadString and Read is that ReadString works only from STDIN and stops at a newline. 

Importantly the console is newline buffered iirc, so as long as you don't put multiple lines in the console Read will function like ReadString.

Importantly, Read is a syscall that exists on real systems whereas I don't think that is true for ReadString.

So, I am in favor of removing ReadString rather than improving the documentation, but I could be convinced that ReadString is worthwhile to keep.

**Comment by Obijuan** [comment]
Thank you very much for your attention :-)

The reason why we use ReadString is because of the pop up dialog that can be activated when the service 8 is called. It is very useful for teaching assembly language to newcomers (we also use the services 5,6,7 and 12 this way)

![screenshot-readstring](https://user-images.githubusercontent.com/1286062/53296595-4635ab80-3812-11e9-81c7-75778eec7ca9.png)

We have been teaching MIPS for many years using the Mars simulator. Now we have changed to Riscv and RARs. It would be great if we can continue using ReadString, or if it is removed, that the Read service could also be configured for the pop up dialog

**Comment by TheThirdOne** [comment]
The fact that ReadString uses a popup hadn't occurred to me. I can see how that could be nice. I have merged it #12 in.

**Comment by Obijuan** [comment]
Thanks a lot 😀
