### ISSUE TITLE
Symbol "printStr" not found in symbol table

### ISSUE THREAD

**Issue by 772** [TheThirdOne/rars#15]
No matter wether I execute the rars.jar on Fedora Linux or on Windows 10: I can not assemble any example code since the system calls aren't working. Mb I am doing something wrong?

Windows:
Error in .......printf.s line 64 column 7: Symbol "printStr" not found in symbol table.
Error in ....bottles.s line 24 column 17: Symbol "printf" not found in symbol table.

**Comment by TheThirdOne** [comment]
`printf`, `printStr`, and `printNum` are all functions defined in other files and need to be loaded in order to use them.

I have normally been doing this by opening all of the needed files and then using the option to assemble all open files. 

I think that I should probably make the examples use includes though so that is clear.

**Comment by TheThirdOne** [comment]
After trying this I see why I didn't develop the examples like that. The `.include` directive is like C's so it causes label collisions. It is really intended for including a set of macros rather than including code.

I may consider adding a new directive which doesn't share a symbol table with the including file. I may also slightly change the semantics of include so that it produces a separate symbol table but shares macros.

**Comment by 772** [comment]
Yes, I tried that yesterday and it worked.
