### ISSUE TITLE
Add a Environment Call like ReadChar but that does not echo (KEY in Forth)

### ISSUE THREAD

**Issue by scotws** [TheThirdOne/rars#153]
The system call `ReadChar` currently echos the character, making it unsuitable for various scenarios such as password entries or games where the key ist just used for movement. This code will result in the character appearing twice: 

```
li a7, 12 # ReadChar
ecall
li a7, 11 # PrintChar
ecall
```

It would be useful to have a system call -- say `ReadKey` -- that accepts the input exactly as `ReadChar` but does not echo. This is the behavior of the `KEY` word in Forth (see https://www.forth.com/starting-forth/10-input-output-operators/) and would allow more low-level simulations.

Unfortunately, if I understand `src/rars/util/SystemIO.java` correctly (unlikely, because I totally suck at Java), this might be rather hard to implement because I'm guessing that `charAt(0)` is reading from buffered input -- in other words, the code would have to bypass the operating system, and a brief Google search shows that there is madness in that direction. It seems that even in C, you need either a non-standard function such as `getch()` (https://www.geeksforgeeks.org/getch-function-in-c-with-examples/) or have to fool around with the terminal settings on Linux. The password routines do not help because they expect a whole string and not just a single keypress. 

Still, maybe I'm missing something? Thanks!

**Comment by TheThirdOne** [comment]
I don't believe you are missing anything. Getting single characters without buffering in a terminal just isn't super easy.

If you want to make a forth interpreter/vm, I would recommend using rv8 or qemu-user, they should both be able to do what you are looking to do and the only downside is less visible debugging. The assembly should be easy enough for that to not be a large problem though.

I am not planning to implement this because it is too much work for a small benefit; there are other issues which are a better use of my time. If you want to make a PR fixing this, you are welcome to.

**Comment by scotws** [comment]
Very understandable. Thanks for the response!
