### ISSUE TITLE
Loading 32-bit Values

### ISSUE THREAD

**Issue by ghost** [TheThirdOne/rars#154]
Goal: set `t1` to `0xAABBCCDD`.

Assembling `li t1, 0xAABBCCDD` expands to

```s
lui x6, 0xfffaabbd
addi x6, x6, 0xfffffcdd
```

Reassembling with the expanded pseudo instruction `li` does not work:

> Error in ... line 1 column 9: "0xfffaabbd": operand is out of range

This works:

```s
lui t1, 0xAABB0
lui t2, 0xCCDD0
srli t2, t2, 16
add t1, t1, t2
```

**Comment by TheThirdOne** [comment]
lui should not be showing a sign-extended immediate. In the case of lui, it doesn't really matter because the there are no extra bits more significant than the immediate, but RARS shouldn't be showing assembly that doesn't compile. I will update the disassembly to make it not sign-extended.

The correct and idiomatic code would be:
```
lui x6, 0xaabbd
addi x6, x6, 0xfffffcdd
```

Writing it like this can be a little tricky because you need to add 1 to the lui immediate whenever the 12th bit of the constant you are trying to load is a 1.

**Comment by TheThirdOne** [comment]
For a thorough explanation of how lui + addi works:
https://stackoverflow.com/questions/50742420/risc-v-build-32-bit-constants-with-lui-and-addi/59546567#59546567
