### ISSUE TITLE
opening rars in linux

### ISSUE THREAD

**Issue by ishitasingh0608** [TheThirdOne/rars#180]
how to open rars in linux?

**Comment by TheThirdOne** [comment]
This is really a question that you should be able to answer for yourself. I would recommend googling something like [this](https://letmegooglethat.com/?q=How+to+open+jar+file+linux).

I cannot even give you more helpful advice than that because I don't know what you might have tried and what specific problems you might have encountered. Adding more information about what you have tried is always a good practice for github issues.
