### ISSUE TITLE
Native Executable

### ISSUE THREAD

**Issue by Rdadamos** [TheThirdOne/rars#184]
I am trying to build a native image from rars.jar, but the instructions are not being loaded as expected. In issue #4 , I saw that there would be a problem with the Classloader, but I couldn't figure out how can I fix it.
I really appreciate some help.

**Comment by TheThirdOne** [comment]
If you cannot figure out the Classloader issues on your own, I cannot really help you other than solving that issue myself. I have yet to do so because I cannot come up with a reason to actually want to build a native image. 

If you have a reason why the native image is better than a jar for you, please comment it on the original issue.
