### ISSUE TITLE
Immediate Out of Range Bug

### ISSUE THREAD

**Issue by BenjaminBeichler** [TheThirdOne/rars#36]
Hi,
I switched from MARS to RARS in my lecture and I got the following error:
in Mars it was totally okay to use to big immediates, which will automatically converted to a LUI and ORI,

e.g. `ori $t0,$t0,0x80000000`

but in RARS that generates an error.

If I try to manually use lui, I even get the error that the operand is out of range:

`lui t0,t0,0x80000`

strangly enough, when I use decimal numbers like

`ori t0,t0,-1`

it works without problems and even do not use an additional lui to assemble the code.

**Comment by TheThirdOne** [comment]
> in Mars it was totally okay to use to big immediates, which will automatically converted to a LUI and ORI,

MIPS has an assembler temporary register `$at` as part of the register convention. RISC-V does not. This means that a psuedo-op to do `ori t0, t0, big` is impossible to assemble without overwriting some unrelated register.

> strangly enough, when I use decimal numbers like `ori t0,t0,-1`

If you used `0xFFFFFFFF` instead of `-1` it would work just as well. All immediate operations operate on signed extended 12 bit  numbers. `-1` fits that whereas  `0x80000000` does not.

```
lui t0,t0,0x80000
```

Should work, and does in gcc. As it turns out, when I rewrote the tests from [riscv/riscv-tests](https://github.com/riscv/riscv-tests/), I accidentally signed extended the `lui` and `auipc` arguments which was my baseline for what correctly formatted assembly was. 

This should be fixed in 1f06f3751dcc196da67fba922229b8eee5cc05b7
