### ISSUE TITLE
Pseudo-instruction JR

### ISSUE THREAD

**Issue by rmnattas** [TheThirdOne/rars#43]
In page 110 of the [RISC-V Specifications](https://content.riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf) the format for the pseudo-instruction `jr` is `jr rs`.

When I used `jr ra` in RARS I got the following error: 
`Too few or incorrectly formatted operands. Expected: jr t0, -100`

I think keeping the format `jr t0, -100` would be beneficial but also supporting the official one is important.

Where does RARS handle pseudo-instruction in the source code?

**Comment by TheThirdOne** [comment]
I though I copied all of the specified psuedo instructions, but it appears I was wrong.

This is handled at
https://github.com/TheThirdOne/rars/blob/6afb2862c460ec777733bf18b5d8a4399a06a251/PseudoOps.txt#L105-L106

Its a two line addition. I can push it up in a few hours.

**Comment by rmnattas** [comment]
@TheThirdOne Would it be possible to make a new release for RARS? I just noticed that the latest release does not include this bug fix but the pre-release does. We would have a group of students download RARS soon (some already did) and we would like for this fix to be included.

**Comment by TheThirdOne** [comment]
@rmnattas, I definitely could make a new release. The reason I made the continuously updated per-release is to make it easy to get access to the latest bugfixes. The main releases are then intended to each have significant developments over the last.

There have been a few small psuedo-op improvemnts and progress on two outstanding issues since v1.3, but thats a pretty small set. What is the reason you are uncomfortable with using the continuous release? If possible, I would like to improve the continuous release system so it could satisfy this kind of request.

**Comment by rmnattas** [comment]
@TheThirdOne We are providing the repo link to students before the terms begin and they mostly will be downloading the latest release instead of the pre-release, and we would prefer if there's a version number (i.e. 1.3.1) to specify and work on.

**Comment by TheThirdOne** [comment]
[v1.3.1](https://github.com/TheThirdOne/rars/releases/tag/v1.3.1) now exists.
