### ISSUE TITLE
UI becomes unresponsive when close Bitmap display while running the program

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [TheThirdOne/rars#48]
A good solution for this problem is: When click to close the bitmap display , first stop the program that are running, after this close bitmap display

**Comment by TheThirdOne** [comment]
I can't reproduce this. Could you give me more information to try to reproduce this? If you could get me a log by launching RARS from the command line, that would be helpful. If you need help doing that, I can give you directions.

My process which doesn't crash:
1. Assemble program 
2. Open bitmap display, prepare settings, and connect to program
3. Run the program at full speed
4. Exit the bitmap display

The program I used to test was:
```
.data
init:		.word	0x10040000
.text
main:
	lw	t0, init 
	li	t2, 0
	li 	t3, 0x100400F0
 loop:
	sb	t2, 2(t0)
	addi t0,t0,4
        ble t0, t3,loop
        addi t2,t2,1
        lw t0, init
        j loop
```

**Comment by PedroAugustoRamalhoDuarte** [comment]
Yes, sure !! I cant get this log, is only java -jar rars in the terminal ?

# Reproduce Error
The code is a little bit big: https://github.com/PedroAugustoRamalhoDuarte/Trabalho1-OAC/blob/master/170099776_170163717_170115810.asm
I did the same step to run the program, when i click to close the Bitmap display the rars dosent responding, do not crash but the rars freeze

**Comment by PedroAugustoRamalhoDuarte** [comment]
The same thing occurs, when try to open the bitmap while the same program is running

**Comment by TheThirdOne** [comment]
I was able to reproduce this with your program. Rather than a crash though, the UI becomes unresponsive.

The technical reason why this happens is that the read string system call is blocking and holds a lock on memory. However the bitmap display or any other tools that inspects memory needs to hold the lock to connect and disconnect from the program.

The solution for this is not simple. There are a bunch of places where the memory lock is acquired within the UI thread; any of those places could cause RARS to hang if a blocking system call is active. And changing blocking system calls so they don't hold a lock to memory is not easy.

**Comment by TheThirdOne** [comment]
This should be fixed now. Let me know if it doesn't work for you. Thanks for the report.

The solution was a little easier than I expected, there were two places in the code were the UI could block the simulation thread. I just had to unlock before waiting from the user and relock after.
