### ISSUE TITLE
Support for Instruction Run and Memory Requests dump

### ISSUE THREAD

**Issue by tv-reddy** [TheThirdOne/rars#58]
It would be great if RARS could support dumping of memory access and instruction traces during run-time so that, these traces can used to generate statistics for branch behaviour, instruction mixing and to design caches. We are using RARS for teaching RISCV programming in an introductory computer architecture class. Please let us know if this issue can be fixed. Thank you very much.

**Comment by jowens** [comment]
Hi @TheThirdOne, I'm the instructor of this course. We had great success with RARS in our first project. What we're hoping to do for the next one is to be able to just dump two things into a file:
- All the instructions that were actually executed, in whatever form is most convenient
- All the memory addresses that were touched, again in whatever form is most convenient
Is this an easy fix / is it any sort of possibility? It would certainly allow some interesting analyses with RARS. Thanks for this nice tool. We've enjoyed teaching with it.

**Comment by TheThirdOne** [comment]
I'm glad RARS has been useful to you.

In case you are not aware, there are integrated tools for interactively exploring branch prediction and cache behavior. They can be accessed from the tools dropdown.

### How this might be implemented

**As a tool**:If you are looking to have a way of getting that data out from the GUI, my recommendation would be to make a tool which can gather the information during execution and then on press of a button output to a file. It shouldn't be very hard as there are several existing tools you could use as examples.

**Through the simulator api**:If you want to make this work automatically the best solution I can think of is using the API to single step through a program and record the information you need.

I'm not sure how big a feature it would be, but if I could make tools run from the command line, I think that would be an ideal way to add this functionality for the command line.

**Internally**: Currently, I don't think there is an easy way to track the information you want internally. The backstepping stack would be the only system that could be rigged to give a log after the fact.Another possible way of getting tracing information is to use the Observer interface, but I have been trying to remove it as much as possible. 

### My role in implementing this

I don't plan to implement the actual logging/tracing behavior because I don't know exactly what is needed and I don't think my experience with the internals of RARS is really needed to do so.

I am open to adding features to help make this functionality work well for you. I plan to look into the tool on command line interface. However, it may take a little time to get around to it as I have been working on floating point stuff recently. 

I suggest that you look into implementing your desired functionality as a tool. All of the included tools can be found in [this directory](https://github.com/TheThirdOne/rars/blob/d4c6acfea1478a82e28b04e4c9bbd9f9749aeb78/src/rars/tools/). In particular, I would suggest looking at [InstructionCounter](https://github.com/TheThirdOne/rars/blob/d4c6acfea1478a82e28b04e4c9bbd9f9749aeb78/src/rars/tools/InstructionCounter.java), [MemoryReferenceVisualization](https://github.com/TheThirdOne/rars/blob/d4c6acfea1478a82e28b04e4c9bbd9f9749aeb78/src/rars/tools/MemoryReferenceVisualization.java) and [BHTSimulation](https://github.com/TheThirdOne/rars/blob/d4c6acfea1478a82e28b04e4c9bbd9f9749aeb78/src/rars/tools/BHTSimulator.java).

For implementing this using the API, you can look at [Test](https://github.com/TheThirdOne/rars/blob/d4c6acfea1478a82e28b04e4c9bbd9f9749aeb78/test/Test.java) and [Launch](https://github.com/TheThirdOne/rars/blob/d4c6acfea1478a82e28b04e4c9bbd9f9749aeb78/src/rars/Launch.java) as examples for how to use it. And the main interface can be found [here](https://github.com/TheThirdOne/rars/tree/d4c6acfea1478a82e28b04e4c9bbd9f9749aeb78/src/rars/api).

If you have trouble figuring out how to write a tool or use the API, please ask questions because they are currently not well documented and documenting them has been on my TODO list.

**Comment by TheThirdOne** [comment]
I noticed there is now a [fork](https://github.com/jowens/rars/) and an implemented tool. Does that tool now suit your needs? If it does, please close this issue.

**Comment by jowens** [comment]
Do you want the tool? It dumps every instruction, every instruction address, and every data address to a file.

**Comment by TheThirdOne** [comment]
@jowens, if you think other people would find the tool useful, then I think it should be included back into the main branch so others can find it easily.  Open a PR if you want to include the tool in RARS.

**Comment by jowens** [comment]
Done (https://github.com/TheThirdOne/rars/pull/68). This is literally my first piece of Java ever; kindly keep that in mind.
