### ISSUE TITLE
RV64IMFD support

### ISSUE THREAD

**Issue by colbac8** [TheThirdOne/rars#60]
Hi, I'm using RARS for teaching scope starting from this year and I would like to know if you are thinking to introduce the support for the RV64I, RV64M, RV64F, and RV64D in the next future.

**Comment by TheThirdOne** [comment]
There are no current plans to support RV64. When I was first porting this I considered supporting RV64, but decided that RV32 would be simpler and almost no value for teaching would be lost by not supporting it.

If there is a specific reason(s) why you feel RV32 is insufficient, please list them here. I still haven't found a need for implementing RV64.

The double extension was in a similar position until recently. I have been exploring adding the D extension to RARS in order to support assembling code from gcc and clang.

**Comment by colbac8** [comment]
The main reason is the compatibility with the Patterson book, which explains the  RV64IAMFD instruction set.

**Comment by TheThirdOne** [comment]
Because RV32 and RV64 are incompatible in several ways, it would take a considerable amount of effort to add a toggle to support RV64. Supporting the Patterson book is not enough reason for me to implement this. There are other features that are easier to implement and would have more significant effects.

If you would like to add this to RARS, open up a PR and I will guide you through implementing it. 

Using another simulator would be another option for you. As far as I am aware, there are no other educational simulators that support RV64, but some of the simulators listed in the [software status](https://riscv.org/software-status/#simulators) do. I'm not really very familiar with most of them, but I know spike supports RV64. I think TinyEMU also does.
