### ISSUE TITLE
Print Double (Service No. 3)

### ISSUE THREAD

**Issue by colbac8** [TheThirdOne/rars#66]
Hi, I'm using the latest version of RARS 1.4 for testing the double extension. I noticed that the print service number 3 (print double) is not implemented. How I can print out a double?

**Comment by TheThirdOne** [comment]
As it stands there isn't a print double system call. I neglected to add it when implementing the double extension. [The system call documentation](https://github.com/TheThirdOne/rars/wiki/Environment-Calls) correctly shows that system call 3 (printDouble) and 7 (readDouble) are both unavailable.

A printf implementation compiled to assembly should work if your goal is making it work with version 1.4

Otherwise, I'll put implementing those system calls on my TODO list. It should be pretty easy to add if someone else wants to jump in though.

**Comment by colbac8** [comment]
ok, thank you. Thank you for the printf hint, I'll test it.

**Comment by TheThirdOne** [comment]
e835ec5efdb65bfeb069e3fd776ec8cfc49b0c23 removed a bunch of double related system calls. Probably all of them can be moved into the current codebase with minor modifications. I would accept a PR for any subset of these calls updated.

The calls as they existed prior to e835ec5efdb65bfeb069e3fd776ec8cfc49b0c23:
  - [InputDialogDouble](https://github.com/TheThirdOne/rars/blob/a38c5d87f0ca93030879e66f21bf20d1bab4f949/mars/mips/instructions/syscalls/SyscallInputDialogDouble.java)
  - [MessageDialogDouble](https://github.com/TheThirdOne/rars/blob/a38c5d87f0ca93030879e66f21bf20d1bab4f949/mars/mips/instructions/syscalls/SyscallMessageDialogDouble.java)
  - [PrintDouble](https://github.com/TheThirdOne/rars/blob/a38c5d87f0ca93030879e66f21bf20d1bab4f949/mars/mips/instructions/syscalls/SyscallPrintDouble.java)
  - [RandDouble](https://github.com/TheThirdOne/rars/blob/a38c5d87f0ca93030879e66f21bf20d1bab4f949/mars/mips/instructions/syscalls/SyscallRandDouble.java)
  - [ReadDouble](https://github.com/TheThirdOne/rars/blob/a38c5d87f0ca93030879e66f21bf20d1bab4f949/mars/mips/instructions/syscalls/SyscallReadDouble.java)

**Comment by TheThirdOne** [comment]
Those five system calls are now available in the continuous release. I haven't tested them much, but they seem to be working.

Let me know if they aren't working right.

**Comment by fudgenuggets12** [comment]
I'll get to it when I can. I do have school.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TheThirdOne/rars/issues/66#issuecomment-616935839>, or
unsubscribe
