### ISSUE TITLE
abs pseudo instruction missing

### ISSUE THREAD

**Issue by uvillano** [TheThirdOne/rars#72]
Comparing RARS to MARS, I have noted the absence of the abs pseudo-instruction present in MARS.

abs $t1,$t2             ABSolute value : Set $t1 to absolute value of $t2 (algorithm from Hacker's Delight) 

It is very useful, and the algorithm really a delight. I think it is worth to be added...

**Comment by TheThirdOne** [comment]
I don't plan on implementing this because: 
  - No current psuedo-instruction uses a branch and this would have to in order to stay short.
    - Technically it would be difficult because #20 has yet to be fixed.
  - GCC does not support it
  - it is not a psuedo-instruction that I think any risc-v assembler supports

If you are working with floats. fabs.s is a valid psuedo-instruction.

I will put more thought into #20 so that it would be possible to implement this if you want to make your own psuedo-instruction.

**Comment by uvillano** [comment]
The beauty of the abs implementation is that it DOES NOT use any branch. The following is the MIPS code generated by the abs pseudo-instruction.

abs $s1,$s2 is translated into:

sra $at,$s2,31
xor $s1,$at,$s2
subu $s1,$s1,$at

Cheers

Umberto

**Comment by TheThirdOne** [comment]
That implementation uses `$at` as a temporary. There is no dedicated temporary in RISC-V. Hence you need a branch or a change to the psuedo-instruction format so that a temporary can be passed in.
