### ISSUE TITLE
Bug in Dump Memory (Text/Data segment window)

### ISSUE THREAD

**Issue by JoseDanielMunozFrias** [TheThirdOne/rars#95]
I have found a bug in the memory dump. The size of the disassembled code is not enough for the instruction addi X28, X28, 0x28. The dump generated is:

0x00000078  0x028e0e13  addi x28,x28,0x000000254   	addi x28, x28, 0x28

And as it can be seen the 8 of the immediate is truncated by the line number.

I think the fix is easy: in file rars/src/rars/riscv/dump/SegmentWindowDumpFormat.java change line 134 from:
                    string += (ps.getPrintableBasicAssemblyStatement() + "                      ").substring(0, 22);
to:
                    string += (ps.getPrintableBasicAssemblyStatement() + "                        ").substring(0, 24);

Best regards.

Daniel

**Comment by TheThirdOne** [comment]
Adding 2 to the amount of padding is insufficient to solve this issue. Particularly long instructions like `fmadd.s f28,f28, f28, f28, rup` would still see this issue.

Adding 6 would probably handle it unless you are looking for an edge case, but it is probably most correct to just properly right justify based on the longest instruction.

**Comment by JoseDanielMunozFrias** [comment]
For me is better to have a dump with the columns fixed because I'm using this dump to generate a filter file for gtkwave in order to see the generated assembly file in the simulation of a RISC-V core I'm using for teaching. This file consist of the machine code and the assembly code, so having the column fixed makes very easy to get these fields from the dump file.

**Comment by TheThirdOne** [comment]
If you want the column to be fixed width and never chop off an instruction, it will need to as wide as maximum length any instruction can be. The widest instruction I have been able to come up with would be `csrrci x28,0x00003202,0x00000010` at 32 characters long.

If I had found this issue on my own, I would probably extend the base length to 26 and if any instruction exceeded that tightly justify. However, because you found this and specifically prefer fixed width columns, I plan to just widen the "Basic" Column to ensure all instructions can fit (a very simple change).

The two questions still in my head are:
1. Can I make the representation of `csrrci` shorter? The immediates are not actually big.   
2. What instructions might be added in the future that would exceed the column size of 32?

**Comment by JoseDanielMunozFrias** [comment]
For my, extending the base length to 26 is OK, because in my simple core I haven't implemented csrrci (it's a core that the students have to implement in one semester and I have removed these instructions for simplicity). On the other hand the last immediate of csrrci is only 5 bits and zero extended, so only 4 bytes are needed.

**Comment by TheThirdOne** [comment]
The answers I have found to my questions:
1. The best way in the code I see is to make 5 bit immediates always print using decimal notation. In that case the next longest instruction would be `fnmadd.s f28,f28,f28,f28,rup` at 28 characters.
2. Its possible the something in the B extension might be long, but A and C both seem to be clear of long instructions.

One other thing to note is that if `csrrci` can still be long, the Basic column of the execute pane in the GUI should have its maximum width increased because that cuts it off.

I see three potential sets of changes that would close this issue.
1. Increase the width of the dump column to 32 and increase the width of the GUI column.
2. Increase the width of the dump column to 28 and shorten 5 bit immediates.
3. Increase the base size of dump column to 26, add resizing the column for large instructions, and increase the width of the GUI Column.

2 is marginally more work than 1, but I think is better in the end. 3 is substantially more code, but would be robust to any future instructions.

**Comment by JoseDanielMunozFrias** [comment]
I also think the option 2 is the best.

If I can help tell me. I'm not an expert on Java, but I have a strong experience in C programming for embedded systems.

Thanks for your work in this great simulator.

**Comment by TheThirdOne** [comment]
@JoseDanielMunozFrias, this should be fixed now. If the [continuous release](https://github.com/TheThirdOne/rars/releases/tag/continuous) doesn't serve your needs, I'll reopen this.

Thank you for making this issue and I hope RARS will continue to be useful to you.

**Comment by JoseDanielMunozFrias** [comment]
I have tested the continuous release and works OK. Thanks!
